# Generated by Django 3.0.5 on 2020-05-04 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('thumbnail', models.ImageField(upload_to='thumbnails/', verbose_name='サムネイル')),
                ('booklog_id', models.CharField(max_length=10, verbose_name='サイトid')),
            ],
        ),
        migrations.CreateModel(
            name='Book1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('img_url', models.CharField(max_length=50, verbose_name='画像')),
                ('no', models.CharField(max_length=10, verbose_name='アイテムNo')),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(default=django.utils.timezone.now, verbose_name='開始時間')),
                ('end', models.DateField(default=django.utils.timezone.now, verbose_name='終了時間')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_site.Book1', verbose_name='タイトル')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='名前')),
            ],
        ),
    ]
