# Generated by Django 3.0.5 on 2020-05-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_site', '0002_auto_20200504_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book1',
            name='title',
            field=models.CharField(max_length=150, verbose_name='タイトル'),
        ),
    ]
